### ISSUE TITLE
Support for reanimated v2 ?

### ISSUE THREAD

**Issue by jaraujocds** [asaeed14/react-native-animated-skeleton#1]
I'm getting `TypeError: undefined is not a function`.
I'm using Reanimated 2.3.1 and Gesture Handler 2.1.0

![image](https://user-images.githubusercontent.com/92323329/149368707-5872e674-4283-4ac8-b637-553b5f16198c.png)

my code:
```
return <Skeleton loaderStyle={styles.flex} numberOfItems={1} />;
```

**Comment by asaeed14** [comment]
react-native-reanimated v2 support added 🚀 now you can use the latest version **0.1.0** 

"Read the updated docs"
